version: "3.8"

services:
  http-server_lab2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http-file-server_lab2
    ports:
      - "3333:3333"
    volumes:
      - .:/srv/files
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - http-network


# 🌐 Custom Docker network (bridge)
networks:
  http-network:
    driver: bridge

#  Define named volumes
volumes:
  shared_files:
  friend_files:
  downloads:
